opt_in_rules: # some rules are only opt-in
  - control_statement
  - empty_count
  - colon
  - comma
  - todo
  - fatal_error_message

disabled_rules:
  - force_cast

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods/
  - Carthage/

file_length:
  warning: 400
  error: 600

line_length:
  warning: 150
  error: 250

type_body_length:
  - 300 # warning
  - 400 # error

large_tuple: # warn user when using 3 values in tuple, give error if there are 4
   - 3
   - 4

type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 40
    error: 45

identifier_name:
  min_length: # only min_length
    error: 2 # only error
  excluded: # excluded via string array
    - id
    - key
    - URL
    - url
    - ids
    - put
    - get
    - sdk
    - now
    - csv
    - int
    - vc
    - to
    - tab
    - nib
    - tr
    - ok
    - lat
    - lng
    - up
    - no
    - me
    - h1
    - h2
    - h3
    - h4
    - h5
    - h6
    - h7

function_parameter_count:
 warning: 8
 error: 15
